// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Street address information for customers, employees, and vendors.
    ///</summary>
    public partial class Address : IEntity<int>
    {

        ///<summary>
        /// Primary key for Address records.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// First street address line.
        ///</summary>
       public string AddressLine1 { get; set; }

        ///<summary>
        /// Second street address line.
        ///</summary>
       public string AddressLine2 { get; set; }

        ///<summary>
        /// Name of the city.
        ///</summary>
       public string City { get; set; }

        ///<summary>
        /// Unique identification number for the state or province. Foreign key to StateProvince table.
        ///</summary>
       public int StateProvinceId { get; set; }

        ///<summary>
        /// Postal code for the street address.
        ///</summary>
       public string PostalCode { get; set; }

        ///<summary>
        /// Latitude and longitude of this address.
        ///</summary>
       public System.Data.Entity.Spatial.DbGeography SpatialLocation { get; set; }

        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
       public System.Guid Rowguid { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<BusinessEntityAddress> BusinessEntityAddresses { get; set; }
        public ICollection<SalesOrderHeader> SalesOrderHeaders_BillToAddressId { get; set; }
        public ICollection<SalesOrderHeader> SalesOrderHeaders_ShipToAddressId { get; set; }


        public StateProvince StateProvince { get; set; }

        public Address()
        {
            Rowguid = System.Guid.NewGuid();
            ModifiedDate = System.DateTime.Now;
            BusinessEntityAddresses = new List<BusinessEntityAddress>();
            SalesOrderHeaders_BillToAddressId = new List<SalesOrderHeader>();
            SalesOrderHeaders_ShipToAddressId = new List<SalesOrderHeader>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
