// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Items required to make bicycles and bicycle subassemblies. It identifies the heirarchical relationship between a parent product and its components.
    ///</summary>
    public partial class BillOfMaterial
    {

        ///<summary>
        /// Primary key for BillOfMaterials records.
        ///</summary>
       public int BillOfMaterialsId { get; set; }

        ///<summary>
        /// Parent product identification number. Foreign key to Product.ProductID.
        ///</summary>
       public int? ProductAssemblyId { get; set; }

        ///<summary>
        /// Component identification number. Foreign key to Product.ProductID.
        ///</summary>
       public int ComponentId { get; set; }

        ///<summary>
        /// Date the component started being used in the assembly item.
        ///</summary>
       public System.DateTime StartDate { get; set; }

        ///<summary>
        /// Date the component stopped being used in the assembly item.
        ///</summary>
       public System.DateTime? EndDate { get; set; }

        ///<summary>
        /// Standard code identifying the unit of measure for the quantity.
        ///</summary>
       public string UnitMeasureCode { get; set; }

        ///<summary>
        /// Indicates the depth the component is from its parent (AssemblyID).
        ///</summary>
       public short BomLevel { get; set; }

        ///<summary>
        /// Quantity of the component needed to create the assembly.
        ///</summary>
       public decimal PerAssemblyQty { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }


        public Product Component { get; set; }

        public Product ProductAssembly { get; set; }

        public UnitMeasure UnitMeasure { get; set; }

        public BillOfMaterial()
        {
            StartDate = System.DateTime.Now;
            ModifiedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
