// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    public partial class BillOfMaterialConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BillOfMaterial>
    {
        public BillOfMaterialConfiguration()
            : this("Production")
        {
        }

        public BillOfMaterialConfiguration(string schema)
        {
            ToTable("BillOfMaterials", schema);
            HasKey(x => x.BillOfMaterialsId);

            Property(x => x.BillOfMaterialsId).HasColumnName(@"BillOfMaterialsID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ProductAssemblyId).HasColumnName(@"ProductAssemblyID").HasColumnType("int").IsOptional();
            Property(x => x.ComponentId).HasColumnName(@"ComponentID").HasColumnType("int").IsRequired();
            Property(x => x.StartDate).HasColumnName(@"StartDate").HasColumnType("datetime").IsRequired();
            Property(x => x.EndDate).HasColumnName(@"EndDate").HasColumnType("datetime").IsOptional();
            Property(x => x.UnitMeasureCode).HasColumnName(@"UnitMeasureCode").HasColumnType("nchar").IsRequired().IsFixedLength().HasMaxLength(3);
            Property(x => x.BomLevel).HasColumnName(@"BOMLevel").HasColumnType("smallint").IsRequired();
            Property(x => x.PerAssemblyQty).HasColumnName(@"PerAssemblyQty").HasColumnType("decimal").IsRequired().HasPrecision(8,2);
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            HasOptional(a => a.ProductAssembly).WithMany(b => b.BillOfMaterials_ProductAssemblyId).HasForeignKey(c => c.ProductAssemblyId).WillCascadeOnDelete(false);
            HasRequired(a => a.Component).WithMany(b => b.BillOfMaterials_ComponentId).HasForeignKey(c => c.ComponentId).WillCascadeOnDelete(false);
            HasRequired(a => a.UnitMeasure).WithMany(b => b.BillOfMaterials).HasForeignKey(c => c.UnitMeasureCode).WillCascadeOnDelete(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
