// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Source of the ID that connects vendors, customers, and employees with address and contact information.
    ///</summary>
    public partial class BusinessEntity : IEntity<int>
    {

        ///<summary>
        /// Primary key for all customers, vendors, and employees.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
       public System.Guid Rowguid { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<BusinessEntityAddress> BusinessEntityAddresses { get; set; }
        public ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; }
        public Person Person { get; set; }
        public Store Store { get; set; }
        public Vendor Vendor { get; set; }

        public BusinessEntity()
        {
            Rowguid = System.Guid.NewGuid();
            ModifiedDate = System.DateTime.Now;
            BusinessEntityAddresses = new List<BusinessEntityAddress>();
            BusinessEntityContacts = new List<BusinessEntityContact>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
