// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Lookup table containing the types of business entity contacts.
    ///</summary>
    public partial class ContactType : IEntity<int>
    {

        ///<summary>
        /// Primary key for ContactType records.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// Contact type description.
        ///</summary>
       public string Name { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; }

        public ContactType()
        {
            ModifiedDate = System.DateTime.Now;
            BusinessEntityContacts = new List<BusinessEntityContact>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
