// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Lookup table containing the ISO standard codes for countries and regions.
    ///</summary>
    public partial class CountryRegion
    {

        ///<summary>
        /// ISO standard code for countries and regions.
        ///</summary>
       public string CountryRegionCode { get; set; }

        ///<summary>
        /// Country or region name.
        ///</summary>
       public string Name { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<CountryRegionCurrency> CountryRegionCurrencies { get; set; }
        public ICollection<SalesTerritory> SalesTerritories { get; set; }
        public ICollection<StateProvince> StateProvinces { get; set; }

        public CountryRegion()
        {
            ModifiedDate = System.DateTime.Now;
            CountryRegionCurrencies = new List<CountryRegionCurrency>();
            SalesTerritories = new List<SalesTerritory>();
            StateProvinces = new List<StateProvince>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
