// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Customer credit card information.
    ///</summary>
    public partial class CreditCard : IEntity<int>
    {

        ///<summary>
        /// Primary key for CreditCard records.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// Credit card name.
        ///</summary>
       public string CardType { get; set; }

        ///<summary>
        /// Credit card number.
        ///</summary>
       public string CardNumber { get; set; }

        ///<summary>
        /// Credit card expiration month.
        ///</summary>
       public byte ExpMonth { get; set; }

        ///<summary>
        /// Credit card expiration year.
        ///</summary>
       public short ExpYear { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<PersonCreditCard> PersonCreditCards { get; set; }
        public ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }

        public CreditCard()
        {
            ModifiedDate = System.DateTime.Now;
            PersonCreditCards = new List<PersonCreditCard>();
            SalesOrderHeaders = new List<SalesOrderHeader>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
