// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Currency exchange rates.
    ///</summary>
    public partial class CurrencyRate : IEntity<int>
    {

        ///<summary>
        /// Primary key for CurrencyRate records.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// Date and time the exchange rate was obtained.
        ///</summary>
       public System.DateTime CurrencyRateDate { get; set; }

        ///<summary>
        /// Exchange rate was converted from this currency code.
        ///</summary>
       public string FromCurrencyCode { get; set; }

        ///<summary>
        /// Exchange rate was converted to this currency code.
        ///</summary>
       public string ToCurrencyCode { get; set; }

        ///<summary>
        /// Average exchange rate for the day.
        ///</summary>
       public decimal AverageRate { get; set; }

        ///<summary>
        /// Final exchange rate for the day.
        ///</summary>
       public decimal EndOfDayRate { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }


        public Currency Currency_FromCurrencyCode { get; set; }

        public Currency Currency_ToCurrencyCode { get; set; }

        public CurrencyRate()
        {
            ModifiedDate = System.DateTime.Now;
            SalesOrderHeaders = new List<SalesOrderHeader>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
