// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Lookup table containing standard ISO currencies.
    ///</summary>
    public partial class Currency
    {

        ///<summary>
        /// The ISO code for the Currency.
        ///</summary>
       public string CurrencyCode { get; set; }

        ///<summary>
        /// Currency name.
        ///</summary>
       public string Name { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<CountryRegionCurrency> CountryRegionCurrencies { get; set; }
        public ICollection<CurrencyRate> CurrencyRates_FromCurrencyCode { get; set; }
        public ICollection<CurrencyRate> CurrencyRates_ToCurrencyCode { get; set; }

        public Currency()
        {
            ModifiedDate = System.DateTime.Now;
            CountryRegionCurrencies = new List<CountryRegionCurrency>();
            CurrencyRates_FromCurrencyCode = new List<CurrencyRate>();
            CurrencyRates_ToCurrencyCode = new List<CurrencyRate>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
