// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Bicycle assembly diagrams.
    ///</summary>
    public partial class Illustration : IEntity<int>
    {

        ///<summary>
        /// Primary key for Illustration records.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// Illustrations used in manufacturing instructions. Stored as XML.
        ///</summary>
       public string Diagram { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<ProductModelIllustration> ProductModelIllustrations { get; set; }

        public Illustration()
        {
            ModifiedDate = System.DateTime.Now;
            ProductModelIllustrations = new List<ProductModelIllustration>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
