// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Product inventory and manufacturing locations.
    ///</summary>
    public partial class Location : IEntity<short>
    {

        ///<summary>
        /// Primary key for Location records.
        ///</summary>
       public short Id { get; set; }

        ///<summary>
        /// Location description.
        ///</summary>
       public string Name { get; set; }

        ///<summary>
        /// Standard hourly cost of the manufacturing location.
        ///</summary>
       public decimal CostRate { get; set; }

        ///<summary>
        /// Work capacity (in hours) of the manufacturing location.
        ///</summary>
       public decimal Availability { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<ProductInventory> ProductInventories { get; set; }
        public ICollection<WorkOrderRouting> WorkOrderRoutings { get; set; }

        public Location()
        {
            ModifiedDate = System.DateTime.Now;
            ProductInventories = new List<ProductInventory>();
            WorkOrderRoutings = new List<WorkOrderRouting>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
