// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Product images.
    ///</summary>
    public partial class ProductPhoto : IEntity<int>
    {

        ///<summary>
        /// Primary key for ProductPhoto records.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// Small image of the product.
        ///</summary>
       public byte[] ThumbNailPhoto { get; set; }

        ///<summary>
        /// Small image file name.
        ///</summary>
       public string ThumbnailPhotoFileName { get; set; }

        ///<summary>
        /// Large image of the product.
        ///</summary>
       public byte[] LargePhoto { get; set; }

        ///<summary>
        /// Large image file name.
        ///</summary>
       public string LargePhotoFileName { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<ProductProductPhoto> ProductProductPhotoes { get; set; }

        public ProductPhoto()
        {
            ModifiedDate = System.DateTime.Now;
            ProductProductPhotoes = new List<ProductProductPhoto>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
