// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Customer reviews of products they have purchased.
    ///</summary>
    public partial class ProductReview : IEntity<int>
    {

        ///<summary>
        /// Primary key for ProductReview records.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// Product identification number. Foreign key to Product.ProductID.
        ///</summary>
       public int ProductId { get; set; }

        ///<summary>
        /// Name of the reviewer.
        ///</summary>
       public string ReviewerName { get; set; }

        ///<summary>
        /// Date review was submitted.
        ///</summary>
       public System.DateTime ReviewDate { get; set; }

        ///<summary>
        /// Reviewer&apos;s e-mail address.
        ///</summary>
       public string EmailAddress { get; set; }

        ///<summary>
        /// Product rating given by the reviewer. Scale is 1 to 5 with 5 as the highest rating.
        ///</summary>
       public int Rating { get; set; }

        ///<summary>
        /// Reviewer&apos;s comments
        ///</summary>
       public string Comments { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }


        public Product Product { get; set; }

        public ProductReview()
        {
            ReviewDate = System.DateTime.Now;
            ModifiedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
