// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Product model classification.
    ///</summary>
    public partial class ProductModel : IEntity<int>
    {

        ///<summary>
        /// Primary key for ProductModel records.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// Product model description.
        ///</summary>
       public string Name { get; set; }

        ///<summary>
        /// Detailed product catalog information in xml format.
        ///</summary>
       public string CatalogDescription { get; set; }

        ///<summary>
        /// Manufacturing instructions in xml format.
        ///</summary>
       public string Instructions { get; set; }

        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
       public System.Guid Rowguid { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<Product> Products { get; set; }
        public ICollection<ProductModelIllustration> ProductModelIllustrations { get; set; }
        public ICollection<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCultures { get; set; }

        public ProductModel()
        {
            Rowguid = System.Guid.NewGuid();
            ModifiedDate = System.DateTime.Now;
            Products = new List<Product>();
            ProductModelIllustrations = new List<ProductModelIllustration>();
            ProductModelProductDescriptionCultures = new List<ProductModelProductDescriptionCulture>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
