// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Individual products associated with a specific purchase order. See PurchaseOrderHeader.
    ///</summary>
    public partial class PurchaseOrderDetail : IEntity<int>
    {

        ///<summary>
        /// Primary key. Foreign key to PurchaseOrderHeader.PurchaseOrderID.
        ///</summary>
       public int PurchaseOrderId { get; set; }

        ///<summary>
        /// Primary key. One line number per purchased product.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// Date the product is expected to be received.
        ///</summary>
       public System.DateTime DueDate { get; set; }

        ///<summary>
        /// Quantity ordered.
        ///</summary>
       public short OrderQty { get; set; }

        ///<summary>
        /// Product identification number. Foreign key to Product.ProductID.
        ///</summary>
       public int ProductId { get; set; }

        ///<summary>
        /// Vendor&apos;s selling price of a single product.
        ///</summary>
       public decimal UnitPrice { get; set; }

        ///<summary>
        /// Per product subtotal. Computed as OrderQty * UnitPrice.
        ///</summary>
       public decimal LineTotal { get; private set; }

        ///<summary>
        /// Quantity actually received from the vendor.
        ///</summary>
       public decimal ReceivedQty { get; set; }

        ///<summary>
        /// Quantity rejected during inspection.
        ///</summary>
       public decimal RejectedQty { get; set; }

        ///<summary>
        /// Quantity accepted into inventory. Computed as ReceivedQty - RejectedQty.
        ///</summary>
       public decimal StockedQty { get; private set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }


        public Product Product { get; set; }

        public PurchaseOrderHeader PurchaseOrderHeader { get; set; }

        public PurchaseOrderDetail()
        {
            ModifiedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
