// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    public partial class SalesTaxRateConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SalesTaxRate>
    {
        public SalesTaxRateConfiguration()
            : this("Sales")
        {
        }

        public SalesTaxRateConfiguration(string schema)
        {
            ToTable("SalesTaxRate", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"SalesTaxRateID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.StateProvinceId).HasColumnName(@"StateProvinceID").HasColumnType("int").IsRequired();
            Property(x => x.TaxType).HasColumnName(@"TaxType").HasColumnType("tinyint").IsRequired();
            Property(x => x.TaxRate).HasColumnName(@"TaxRate").HasColumnType("smallmoney").IsRequired().HasPrecision(10,4);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Rowguid).HasColumnName(@"rowguid").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsRequired();

            HasRequired(a => a.StateProvince).WithMany(b => b.SalesTaxRates).HasForeignKey(c => c.StateProvinceId).WillCascadeOnDelete(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
