// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Tax rate lookup table.
    ///</summary>
    public partial class SalesTaxRate : IEntity<int>
    {

        ///<summary>
        /// Primary key for SalesTaxRate records.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// State, province, or country/region the sales tax applies to.
        ///</summary>
       public int StateProvinceId { get; set; }

        ///<summary>
        /// 1 = Tax applied to retail transactions, 2 = Tax applied to wholesale transactions, 3 = Tax applied to all sales (retail and wholesale) transactions.
        ///</summary>
       public byte TaxType { get; set; }

        ///<summary>
        /// Tax rate amount.
        ///</summary>
       public decimal TaxRate { get; set; }

        ///<summary>
        /// Tax rate description.
        ///</summary>
       public string Name { get; set; }

        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
       public System.Guid Rowguid { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }


        public StateProvince StateProvince { get; set; }

        public SalesTaxRate()
        {
            Rowguid = System.Guid.NewGuid();
            ModifiedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
