// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Sales territory lookup table.
    ///</summary>
    public partial class SalesTerritory
    {

        ///<summary>
        /// Primary key for SalesTerritory records.
        ///</summary>
       public int TerritoryId { get; set; }

        ///<summary>
        /// Sales territory description
        ///</summary>
       public string Name { get; set; }

        ///<summary>
        /// ISO standard country or region code. Foreign key to CountryRegion.CountryRegionCode.
        ///</summary>
       public string CountryRegionCode { get; set; }

        ///<summary>
        /// Geographic area to which the sales territory belong.
        ///</summary>
       public string Group { get; set; }

        ///<summary>
        /// Sales in the territory year to date.
        ///</summary>
       public decimal SalesYtd { get; set; }

        ///<summary>
        /// Sales in the territory the previous year.
        ///</summary>
       public decimal SalesLastYear { get; set; }

        ///<summary>
        /// Business costs in the territory year to date.
        ///</summary>
       public decimal CostYtd { get; set; }

        ///<summary>
        /// Business costs in the territory the previous year.
        ///</summary>
       public decimal CostLastYear { get; set; }

        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
       public System.Guid Rowguid { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<Customer> Customers { get; set; }
        public ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
        public ICollection<SalesPerson> SalesPersons { get; set; }
        public ICollection<SalesTerritoryHistory> SalesTerritoryHistories { get; set; }
        public ICollection<StateProvince> StateProvinces { get; set; }


        public CountryRegion CountryRegion { get; set; }

        public SalesTerritory()
        {
            Rowguid = System.Guid.NewGuid();
            ModifiedDate = System.DateTime.Now;
            Customers = new List<Customer>();
            SalesOrderHeaders = new List<SalesOrderHeader>();
            SalesPersons = new List<SalesPerson>();
            SalesTerritoryHistories = new List<SalesTerritoryHistory>();
            StateProvinces = new List<StateProvince>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
