// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Manufacturing failure reasons lookup table.
    ///</summary>
    public partial class ScrapReason : IEntity<short>
    {

        ///<summary>
        /// Primary key for ScrapReason records.
        ///</summary>
       public short Id { get; set; }

        ///<summary>
        /// Failure description.
        ///</summary>
       public string Name { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<WorkOrder> WorkOrders { get; set; }

        public ScrapReason()
        {
            ModifiedDate = System.DateTime.Now;
            WorkOrders = new List<WorkOrder>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
