// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Work shift lookup table.
    ///</summary>
    public partial class Shift : IEntity<byte>
    {

        ///<summary>
        /// Primary key for Shift records.
        ///</summary>
       public byte Id { get; set; }

        ///<summary>
        /// Shift description.
        ///</summary>
       public string Name { get; set; }

        ///<summary>
        /// Shift start time.
        ///</summary>
       public System.TimeSpan StartTime { get; set; }

        ///<summary>
        /// Shift end time.
        ///</summary>
       public System.TimeSpan EndTime { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<EmployeeDepartmentHistory> EmployeeDepartmentHistories { get; set; }

        public Shift()
        {
            ModifiedDate = System.DateTime.Now;
            EmployeeDepartmentHistories = new List<EmployeeDepartmentHistory>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
