// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Contains online customer orders until the order is submitted or cancelled.
    ///</summary>
    public partial class ShoppingCartItem : IEntity<int>
    {

        ///<summary>
        /// Primary key for ShoppingCartItem records.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// Shopping cart identification number.
        ///</summary>
       public string ShoppingCartId { get; set; }

        ///<summary>
        /// Product quantity ordered.
        ///</summary>
       public int Quantity { get; set; }

        ///<summary>
        /// Product ordered. Foreign key to Product.ProductID.
        ///</summary>
       public int ProductId { get; set; }

        ///<summary>
        /// Date the time the record was created.
        ///</summary>
       public System.DateTime DateCreated { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }


        public Product Product { get; set; }

        public ShoppingCartItem()
        {
            Quantity = 1;
            DateCreated = System.DateTime.Now;
            ModifiedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
