// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Sale discounts lookup table.
    ///</summary>
    public partial class SpecialOffer : IEntity<int>
    {

        ///<summary>
        /// Primary key for SpecialOffer records.
        ///</summary>
       public int Id { get; set; }

        ///<summary>
        /// Discount description.
        ///</summary>
       public string Description { get; set; }

        ///<summary>
        /// Discount precentage.
        ///</summary>
       public decimal DiscountPct { get; set; }

        ///<summary>
        /// Discount type category.
        ///</summary>
       public string Type { get; set; }

        ///<summary>
        /// Group the discount applies to such as Reseller or Customer.
        ///</summary>
       public string Category { get; set; }

        ///<summary>
        /// Discount start date.
        ///</summary>
       public System.DateTime StartDate { get; set; }

        ///<summary>
        /// Discount end date.
        ///</summary>
       public System.DateTime EndDate { get; set; }

        ///<summary>
        /// Minimum discount percent allowed.
        ///</summary>
       public int MinQty { get; set; }

        ///<summary>
        /// Maximum discount percent allowed.
        ///</summary>
       public int? MaxQty { get; set; }

        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
       public System.Guid Rowguid { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<SpecialOfferProduct> SpecialOfferProducts { get; set; }

        public SpecialOffer()
        {
            MinQty = 0;
            Rowguid = System.Guid.NewGuid();
            ModifiedDate = System.DateTime.Now;
            SpecialOfferProducts = new List<SpecialOfferProduct>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
