// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Unit of measure lookup table.
    ///</summary>
    public partial class UnitMeasure
    {

        ///<summary>
        /// Primary key.
        ///</summary>
       public string UnitMeasureCode { get; set; }

        ///<summary>
        /// Unit of measure description.
        ///</summary>
       public string Name { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }

        public ICollection<BillOfMaterial> BillOfMaterials { get; set; }
        public ICollection<Product> Products_SizeUnitMeasureCode { get; set; }
        public ICollection<Product> Products_WeightUnitMeasureCode { get; set; }
        public ICollection<ProductVendor> ProductVendors { get; set; }

        public UnitMeasure()
        {
            ModifiedDate = System.DateTime.Now;
            BillOfMaterials = new List<BillOfMaterial>();
            Products_SizeUnitMeasureCode = new List<Product>();
            Products_WeightUnitMeasureCode = new List<Product>();
            ProductVendors = new List<ProductVendor>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
