// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    public partial class VAdditionalContactInfo
    {
       public int BusinessEntityId { get; set; }
       public string FirstName { get; set; }
       public string MiddleName { get; set; }
       public string LastName { get; set; }
       public string TelephoneNumber { get; set; }
       public string TelephoneSpecialInstructions { get; set; }
       public string Street { get; set; }
       public string City { get; set; }
       public string StateProvince { get; set; }
       public string PostalCode { get; set; }
       public string CountryRegion { get; set; }
       public string HomeAddressSpecialInstructions { get; set; }
       public string EMailAddress { get; set; }
       public string EMailSpecialInstructions { get; set; }
       public string EMailTelephoneNumber { get; set; }
       public System.Guid Rowguid { get; set; }
       public System.DateTime ModifiedDate { get; set; }

        public VAdditionalContactInfo()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
