// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    public partial class VEmployeeDepartment
    {
       public int BusinessEntityId { get; set; }
       public string Title { get; set; }
       public string FirstName { get; set; }
       public string MiddleName { get; set; }
       public string LastName { get; set; }
       public string Suffix { get; set; }
       public string JobTitle { get; set; }
       public string Department { get; set; }
       public string GroupName { get; set; }
       public System.DateTime StartDate { get; set; }

        public VEmployeeDepartment()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
