// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    public partial class VJobCandidateEmployment
    {
       public int JobCandidateId { get; set; }
       public System.DateTime? Emp46StartDate { get; set; }
       public System.DateTime? Emp46EndDate { get; set; }
       public string Emp46OrgName { get; set; }
       public string Emp46JobTitle { get; set; }
       public string Emp46Responsibility { get; set; }
       public string Emp46FunctionCategory { get; set; }
       public string Emp46IndustryCategory { get; set; }
       public string Emp46Loc46CountryRegion { get; set; }
       public string Emp46Loc46State { get; set; }
       public string Emp46Loc46City { get; set; }

        public VJobCandidateEmployment()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
