// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    public partial class VJobCandidate
    {
       public int JobCandidateId { get; set; }
       public int? BusinessEntityId { get; set; }
       public string Name46Prefix { get; set; }
       public string Name46First { get; set; }
       public string Name46Middle { get; set; }
       public string Name46Last { get; set; }
       public string Name46Suffix { get; set; }
       public string Skills { get; set; }
       public string Addr46Type { get; set; }
       public string Addr46Loc46CountryRegion { get; set; }
       public string Addr46Loc46State { get; set; }
       public string Addr46Loc46City { get; set; }
       public string Addr46PostalCode { get; set; }
       public string EMail { get; set; }
       public string WebSite { get; set; }
       public System.DateTime ModifiedDate { get; set; }

        public VJobCandidate()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
