// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    public partial class VJobCandidateEducation
    {
       public int JobCandidateId { get; set; }
       public string Edu46Level { get; set; }
       public System.DateTime? Edu46StartDate { get; set; }
       public System.DateTime? Edu46EndDate { get; set; }
       public string Edu46Degree { get; set; }
       public string Edu46Major { get; set; }
       public string Edu46Minor { get; set; }
       public string Edu46Gpa { get; set; }
       public string Edu46GpaScale { get; set; }
       public string Edu46School { get; set; }
       public string Edu46Loc46CountryRegion { get; set; }
       public string Edu46Loc46State { get; set; }
       public string Edu46Loc46City { get; set; }

        public VJobCandidateEducation()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
