// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    public partial class VPersonDemographic
    {
       public int BusinessEntityId { get; set; }
       public decimal? TotalPurchaseYtd { get; set; }
       public System.DateTime? DateFirstPurchase { get; set; }
       public System.DateTime? BirthDate { get; set; }
       public string MaritalStatus { get; set; }
       public string YearlyIncome { get; set; }
       public string Gender { get; set; }
       public int? TotalChildren { get; set; }
       public int? NumberChildrenAtHome { get; set; }
       public string Education { get; set; }
       public string Occupation { get; set; }
       public bool? HomeOwnerFlag { get; set; }
       public int? NumberCarsOwned { get; set; }

        public VPersonDemographic()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
