// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    public partial class VProductAndDescription
    {
       public int ProductId { get; set; }
       public string Name { get; set; }
       public string ProductModel { get; set; }
       public string CultureId { get; set; }
       public string Description { get; set; }

        public VProductAndDescription()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
