// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    public partial class VProductModelInstruction
    {
       public int ProductModelId { get; set; }
       public string Name { get; set; }
       public string Instructions { get; set; }
       public int? LocationId { get; set; }
       public decimal? SetupHours { get; set; }
       public decimal? MachineHours { get; set; }
       public decimal? LaborHours { get; set; }
       public int? LotSize { get; set; }
       public string Step { get; set; }
       public System.Guid Rowguid { get; set; }
       public System.DateTime ModifiedDate { get; set; }

        public VProductModelInstruction()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
