// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    public partial class VSalesPersonSalesByFiscalYear
    {
       public int? SalesPersonId { get; set; }
       public string FullName { get; set; }
       public string JobTitle { get; set; }
       public string SalesTerritory { get; set; }
       public decimal? C2002 { get; set; }
       public decimal? C2003 { get; set; }
       public decimal? C2004 { get; set; }

        public VSalesPersonSalesByFiscalYear()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
