// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRUD.Infrastructure.POCOs
{
    using System;
    using System.Collections.Generic;

    ///<summary>
    /// Work order details.
    ///</summary>
    public partial class WorkOrderRouting
    {

        ///<summary>
        /// Primary key. Foreign key to WorkOrder.WorkOrderID.
        ///</summary>
       public int WorkOrderId { get; set; }

        ///<summary>
        /// Primary key. Foreign key to Product.ProductID.
        ///</summary>
       public int ProductId { get; set; }

        ///<summary>
        /// Primary key. Indicates the manufacturing process sequence.
        ///</summary>
       public short OperationSequence { get; set; }

        ///<summary>
        /// Manufacturing location where the part is processed. Foreign key to Location.LocationID.
        ///</summary>
       public short LocationId { get; set; }

        ///<summary>
        /// Planned manufacturing start date.
        ///</summary>
       public System.DateTime ScheduledStartDate { get; set; }

        ///<summary>
        /// Planned manufacturing end date.
        ///</summary>
       public System.DateTime ScheduledEndDate { get; set; }

        ///<summary>
        /// Actual start date.
        ///</summary>
       public System.DateTime? ActualStartDate { get; set; }

        ///<summary>
        /// Actual end date.
        ///</summary>
       public System.DateTime? ActualEndDate { get; set; }

        ///<summary>
        /// Number of manufacturing hours used.
        ///</summary>
       public decimal? ActualResourceHrs { get; set; }

        ///<summary>
        /// Estimated manufacturing cost.
        ///</summary>
       public decimal PlannedCost { get; set; }

        ///<summary>
        /// Actual manufacturing cost.
        ///</summary>
       public decimal? ActualCost { get; set; }

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
       public System.DateTime ModifiedDate { get; set; }


        public Location Location { get; set; }

        public WorkOrder WorkOrder { get; set; }

        public WorkOrderRouting()
        {
            ModifiedDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
